sudo: required
language: node_js
branches:
  only:
  - develop
  - master
node_js:
- '0.12'
cache:
  directories:
    - ~/.meteor
before_install:
- npm install -g npm@'>=2.13.5'
- mkdir -p node_modules
install:
- curl https://install.meteor.com | /bin/sh
before_script:
- mkdir /tmp/build
script:
- meteor build /tmp/build
before_deploy:
- mkdir /tmp/deploy
- .travis/namefiles.sh
- .travis/sandstorm.sh
deploy:
  - provider: s3
    access_key_id: "AKIAIKIA7H7D47KUHYCA"
    secret_access_key: $ACCESSKEY
    bucket: "rocketchatbuild"
    skip_cleanup: true
    local_dir: /tmp/deploy
    on:
      branch:
      - master
      - develop
after_deploy:
- .travis/docker.sh
